### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by Moxinilian** [miscreant/miscreant.rs#47]
Miscreant is unfortunately really hard to use without a bit more documentation, and examples would in my opinion work best here.

An example of lacking documentation is the `ad` parameter in methods of the `Encryptor` type. What is it?

**Comment by tarcieri** [comment]
For what it's worth, the Rust implementation of Miscreant is now little more than a wrapper around the [`aes-siv`](https://docs.rs/aes-siv/) crate, which is better maintained / documented.
